version: '3'
services:
  frontend:
    build:
      context: ./react-frontend
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ./fastapi-backend
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/www.vaifalwednesday.com/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/www.vaifalwednesday.com/privkey.pem:/etc/ssl/private/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    restart: always
