version: '3'

services:
  frontend:
    build:
      context: ./react-frontend
    command: sh -c "npm run build && npx serve -s build"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - default

  backend:
    build:
      context: ./fastapi-backend
    ports:
      - "8000:8000"
    restart: always
    networks:
      - default

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - default

networks:
  default:
    driver: bridge
