version: '3.8'

services:
  react-frontend:
    container_name: react-frontend
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  fastapi-backend:
    container_name: fastapi-backend
    build:
      context: ./fastapi-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - react-frontend
      - fastapi-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
