version: '3'

services:
  frontend:
    build:
      context: ./react-frontend
    ports:
      - "8080:80"  # Map container port 80 to host port 8080 to avoid conflict with nginx
    restart: always

  backend:
    build:
      context: ./fastapi-backend
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/www.vaifalwednesday.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/www.vaifalwednesday.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
    ports:
      - "80:80"    # HTTP port
      - "443:443"  # HTTPS port
    restart: always

networks:
  default:
    external:
      name: react-fastapi-digitalocean-deploy_default
